# global settings
title: "Open Standards"
description: "Open source community-driven standards."
#url: "https://standards.github.io"
url: "http://localhost:4000"
repository: Standards/standards.github.io
analytics_account: "UA-91790856-1"

# build settings
exclude: ["vendor", "bower.json", "README.md", "package.json"]
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-github-metadata

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: standard-page
      permalink: /:path/

sass:
  style: :compressed

excluded_pages: ["Explore", "Learn", "Meta", "Not found", "Home", "Styles"]
