# global settings
title: "GitHub Standards"
description: "Make open-source better, together. Collaboration on conventions towards world-wide community standards."
url: "https://standards.github.io"
#url: "http://localhost:4000"
analytics_account: "UA-91790856-1"

# build settings
exclude: ["vendor", "bower.json", "README.md", "package.json"]
markdown: kramdown
gems:
  - jekyll-seo-tag

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
    values:
      image: "https://standards.github.io/resources/images/gh-standards-logo.png"

excluded_repos: ["standards.github.io", "resources", "meta"]